name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: iterative/setup-cml@v1
        with:
          version: 'latest'
      - name: Train model and reports
        env:
          REPO_TOKEN: ${{secrets.TOKEN}}
        run: 
          |
          pip install -r requirements.txt
          python train.py

          cat metrics.txt >> report.md
          echo "![](./plot.png)" >> report.md
          cml comment create report.md
          
